version: '3.9'

services:
  apm01:
    image: apm/apm-server:${APM_VERSION}
    container_name: apm01
    env_file: .env
    ports:
      - ${APM_OUTBOUND_PORT}:8200
    volumes:
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
      - certs:$CERTS_DIR
    networks:
      - elastic

volumes:
  certs:
    external: true
    name: elastic-certs

networks:
  elastic:
    external: true
    name: elastic-net
